name: Publish Blazor WASM to GITHUB
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
        # uses GitHub's checkout action to checkout code form the master branch
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3.0.3
          with:
            # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
            dotnet-version: 7
         # publishes Blazor project to the release-folder
        - name: Publish .NET Core Project
          run: dotnet publish MeowiRo.csproj -c Release -o release --nologo
          
        - name: Github Pages Deploy Action
          # You may pin to the exact commit or the version.
          # uses: avinal/github-pages-deploy-action@7702e2ad1f82097323b08b428c8f57cb21dd965b
          uses: avinal/github-pages-deploy-action@v0.9
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: meowiro-pages
            FOLDER: release/wwwroot
          
          
            

    
